# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42bbd65f7d5df658cd79026ce42a2fe35da0d77647856901c2a936ef3323aeabf9abd0da2d5fe34f6b80630605d408499d7655c3d2540c1390be339f35526a25

test:
  secret_key_base: 4ead662f58b4d8e2bdfc277fee06233bf796f3dd6134e76d3fb9c69f5be3008313fe7de316907abbc307608671f708f2395c18b6f8e1cbda09370eb8923f2025

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
